def get_pose_part(index):
    keypoints = {0: "Nose",
                 1: "LEye",
                 2: "REye",
                 3: "LEar",
                 4: "REar",
                 5: "LShoulder",
                 6: "RShoulder",
                 7: "LElbow",
                 8: "RElbow",
                 9: "LWrist",
                 10: "RWrist",
                 11: "LHip",
                 12: "RHip",
                 13: "LKnee",
                 14: "Rknee",
                 15: "LAnkle",
                 16: "RAnkle"}
    return keypoints[index]
